2020-01-07 21:21:25,094 ERROR: Exception on /search [GET] [in /home/solar/PycharmProjects/microblog_flask/venv/lib/python3.8/site-packages/flask/app.py:1890]
Traceback (most recent call last):
  File "/home/solar/PycharmProjects/microblog_flask/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 706, in comparator
    comparator_factory = self.type.comparator_factory
AttributeError: 'NoneType' object has no attribute 'comparator_factory'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/solar/PycharmProjects/microblog_flask/venv/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/solar/PycharmProjects/microblog_flask/venv/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/solar/PycharmProjects/microblog_flask/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/solar/PycharmProjects/microblog_flask/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/solar/PycharmProjects/microblog_flask/venv/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/solar/PycharmProjects/microblog_flask/venv/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/solar/PycharmProjects/microblog_flask/venv/lib/python3.8/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/solar/PycharmProjects/microblog_flask/app/main/routes.py", line 141, in search
    posts, total = Post.search(g.search_form.q.data, page,
  File "/home/solar/PycharmProjects/microblog_flask/app/models.py", line 21, in search
    return cls.query.filter(cls.id.in_(ids)).order_by(
  File "<string>", line 2, in order_by
  File "/home/solar/PycharmProjects/microblog_flask/venv/lib/python3.8/site-packages/sqlalchemy/orm/base.py", line 220, in generate
    fn(self, *args[1:], **kw)
  File "/home/solar/PycharmProjects/microblog_flask/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 1850, in order_by
    criterion = self._adapt_col_list(criterion)
  File "/home/solar/PycharmProjects/microblog_flask/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 308, in _adapt_col_list
    return [
  File "/home/solar/PycharmProjects/microblog_flask/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 310, in <listcomp>
    expression._literal_as_label_reference(o), True, True
  File "/home/solar/PycharmProjects/microblog_flask/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 4533, in _literal_as_label_reference
    elif hasattr(element, "__clause_element__"):
  File "/home/solar/PycharmProjects/microblog_flask/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 717, in __getattr__
    return getattr(self.comparator, key)
  File "/home/solar/PycharmProjects/microblog_flask/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 855, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/home/solar/PycharmProjects/microblog_flask/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 708, in comparator
    raise TypeError(
TypeError: Object None associated with '.type' attribute is not a TypeEngine class or object
