2019-12-14 21:37:44,370 ERROR: Exception on /reset_password_request [POST] [in /home/solar/PycharmProjects/microblog_flask/venv/lib/python3.8/site-packages/flask/app.py:1890]
Traceback (most recent call last):
  File "/home/solar/PycharmProjects/microblog_flask/venv/lib/python3.8/site-packages/flask_mail.py", line 492, in send
    message.send(connection)
  File "/home/solar/PycharmProjects/microblog_flask/venv/lib/python3.8/site-packages/flask_mail.py", line 427, in send
    connection.send(self)
  File "/home/solar/PycharmProjects/microblog_flask/venv/lib/python3.8/site-packages/flask_mail.py", line 188, in send
    self.host.sendmail(sanitize_address(envelope_from or message.sender),
  File "/usr/lib/python3.8/smtplib.py", line 856, in sendmail
    self.ehlo_or_helo_if_needed()
  File "/usr/lib/python3.8/smtplib.py", line 604, in ehlo_or_helo_if_needed
    if not (200 <= self.ehlo()[0] <= 299):
  File "/usr/lib/python3.8/smtplib.py", line 444, in ehlo
    self.putcmd(self.ehlo_msg, name or self.local_hostname)
  File "/usr/lib/python3.8/smtplib.py", line 371, in putcmd
    self.send(str)
  File "/usr/lib/python3.8/smtplib.py", line 363, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/solar/PycharmProjects/microblog_flask/venv/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/solar/PycharmProjects/microblog_flask/venv/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/solar/PycharmProjects/microblog_flask/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/solar/PycharmProjects/microblog_flask/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/solar/PycharmProjects/microblog_flask/venv/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/solar/PycharmProjects/microblog_flask/venv/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/solar/PycharmProjects/microblog_flask/app/routes.py", line 167, in reset_password_request
    send_password_reset_email(user)
  File "/home/solar/PycharmProjects/microblog_flask/app/email.py", line 14, in send_password_reset_email
    send_email('[Microblog] Reset Your Password',
  File "/home/solar/PycharmProjects/microblog_flask/app/email.py", line 10, in send_email
    mail.send(msg)
  File "/home/solar/PycharmProjects/microblog_flask/venv/lib/python3.8/site-packages/flask_mail.py", line 492, in send
    message.send(connection)
  File "/home/solar/PycharmProjects/microblog_flask/venv/lib/python3.8/site-packages/flask_mail.py", line 152, in __exit__
    self.host.quit()
  File "/usr/lib/python3.8/smtplib.py", line 988, in quit
    res = self.docmd("quit")
  File "/usr/lib/python3.8/smtplib.py", line 424, in docmd
    self.putcmd(cmd, args)
  File "/usr/lib/python3.8/smtplib.py", line 371, in putcmd
    self.send(str)
  File "/usr/lib/python3.8/smtplib.py", line 363, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first
2019-12-14 21:50:12,660 INFO: Microblog startup [in /home/solar/PycharmProjects/microblog_flask/app/__init__.py:47]
